function Jb = autoGen_J_body(q1,q2,q3)
%AUTOGEN_J_BODY
%    JB = AUTOGEN_J_BODY(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Jun-2020 11:59:03

t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t11 = t2.*(8.9e+1./2.0e+2);
t10 = -t9;
t13 = t11-8.9e+1./2.0e+2;
t12 = t6+t10;
Jb = reshape([-t7-t8,0.0,t12,0.0,-t12.*(t3.*(5.7e+1./2.0e+2)-t9.*(8.9e+1./2.0e+2)+t3.*t13-5.7e+1./2.0e+2)-(t7+t8).*(t5.*(5.7e+1./2.0e+2)+t8.*(8.9e+1./2.0e+2)+t5.*t13)+8.9e+1./2.0e+2,0.0,0.0,1.0,0.0,t5.*(4.0./2.5e+1),0.0,t3.*(-4.0./2.5e+1)-5.7e+1./2.0e+2,0.0,1.0,0.0,0.0,0.0,-5.7e+1./2.0e+2],[6,3]);
