function fk_space = autoGen_fk_space(q1,q2,q3)
%AUTOGEN_FK_SPACE
%    FK_SPACE = AUTOGEN_FK_SPACE(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Jun-2020 11:59:03

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = q2+q3;
t6 = cos(t5);
t7 = sin(t5);
t8 = t3.*(4.0./2.5e+1);
t9 = t6.*(5.7e+1./2.0e+2);
t10 = t8+t9;
fk_space = reshape([t2.*t6,t4.*t6,-t7,0.0,-t4,t2,0.0,0.0,t2.*t7,t4.*t7,t6,0.0,t2.*t10,t4.*t10,t7.*(-5.7e+1./2.0e+2)-sin(q2).*(4.0./2.5e+1),1.0],[4,4]);
