function Js = autoGen_J_space(q1,q2,q3)
%AUTOGEN_J_SPACE
%    JS = AUTOGEN_J_SPACE(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Jun-2020 11:59:03

t2 = cos(q1);
t3 = sin(q1);
t4 = sin(q2);
t5 = -t3;
Js = reshape([0.0,0.0,1.0,0.0,0.0,0.0,t5,t2,0.0,0.0,0.0,0.0,t5,t2,0.0,t2.*t4.*(4.0./2.5e+1),t3.*t4.*(4.0./2.5e+1),cos(q2).*(4.0./2.5e+1)],[6,3]);
