/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_quad_LQR_B_func_code_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, nnz, is_sparse, c, k;
  const casadi_int *colind, *row;
  size_t p_nrow, p_ncol;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  nnz = sp[ncol];
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch.");
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, nnz, c, k;
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  nnz = sp[ncol];
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[87] = {24, 24, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 6, 9, 10, 11, 7, 9, 10, 11, 8, 9, 10, 11, 6, 9, 10, 11, 7, 9, 10, 11, 8, 9, 10, 11, 6, 9, 10, 11, 7, 9, 10, 11, 8, 9, 10, 11, 6, 9, 10, 11, 7, 9, 10, 11, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};

/* quad_LQR_B_func:(i0[24],i1[24],i2[4])->(o0[24x24,60nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=6.6852248508526335e-02;
  a1=arg[2]? arg[2][0] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][0]=a2;
  a2=8.6573059546032525e+00;
  a3=arg[0]? arg[0][5] : 0;
  a4=cos(a3);
  a5=arg[0]? arg[0][4] : 0;
  a6=sin(a5);
  a7=(a4*a6);
  a8=arg[0]? arg[0][3] : 0;
  a9=sin(a8);
  a10=(a7*a9);
  a11=sin(a3);
  a12=cos(a8);
  a13=(a11*a12);
  a10=(a10-a13);
  a13=arg[0]? arg[0][12] : 0;
  a14=arg[0]? arg[0][0] : 0;
  a13=(a13-a14);
  a15=(a10*a13);
  a16=cos(a3);
  a12=(a16*a12);
  a3=sin(a3);
  a6=(a3*a6);
  a17=(a6*a9);
  a12=(a12+a17);
  a17=arg[0]? arg[0][13] : 0;
  a18=arg[0]? arg[0][1] : 0;
  a17=(a17-a18);
  a19=(a12*a17);
  a15=(a15+a19);
  a19=cos(a5);
  a9=(a19*a9);
  a20=arg[0]? arg[0][14] : 0;
  a21=arg[0]? arg[0][2] : 0;
  a20=(a20-a21);
  a22=(a9*a20);
  a15=(a15+a22);
  a22=(a1*a15);
  a23=sin(a8);
  a11=(a11*a23);
  a8=cos(a8);
  a7=(a7*a8);
  a11=(a11+a7);
  a7=(a22*a11);
  a24=(a11*a13);
  a6=(a6*a8);
  a16=(a16*a23);
  a6=(a6-a16);
  a16=(a6*a17);
  a24=(a24+a16);
  a19=(a19*a8);
  a8=(a19*a20);
  a24=(a24+a8);
  a8=(a1*a24);
  a16=(a8*a10);
  a7=(a7-a16);
  a7=(a2*a7);
  if (res[0]!=0) res[0][1]=a7;
  a7=6.1100810532802123e+00;
  a24=(a1*a24);
  a16=cos(a5);
  a4=(a4*a16);
  a23=(a24*a4);
  a13=(a4*a13);
  a3=(a3*a16);
  a17=(a3*a17);
  a13=(a13+a17);
  a5=sin(a5);
  a20=(a5*a20);
  a13=(a13-a20);
  a20=(a1*a13);
  a17=(a20*a11);
  a23=(a23-a17);
  a23=(a7*a23);
  if (res[0]!=0) res[0][2]=a23;
  a23=4.2924059933577166e+00;
  a13=(a1*a13);
  a17=(a13*a10);
  a15=(a1*a15);
  a16=(a15*a4);
  a17=(a17-a16);
  a17=(a23*a17);
  if (res[0]!=0) res[0][3]=a17;
  a17=(a0*a1);
  if (res[0]!=0) res[0][4]=a17;
  a17=(a22*a6);
  a16=(a8*a12);
  a17=(a17-a16);
  a17=(a2*a17);
  if (res[0]!=0) res[0][5]=a17;
  a17=(a24*a3);
  a16=(a20*a6);
  a17=(a17-a16);
  a17=(a7*a17);
  if (res[0]!=0) res[0][6]=a17;
  a17=(a13*a12);
  a16=(a15*a3);
  a17=(a17-a16);
  a17=(a23*a17);
  if (res[0]!=0) res[0][7]=a17;
  a1=(a0*a1);
  if (res[0]!=0) res[0][8]=a1;
  a22=(a22*a19);
  a8=(a8*a9);
  a22=(a22-a8);
  a22=(a2*a22);
  if (res[0]!=0) res[0][9]=a22;
  a22=-6.1100810532802123e+00;
  a24=(a24*a5);
  a20=(a20*a19);
  a24=(a24+a20);
  a24=(a22*a24);
  if (res[0]!=0) res[0][10]=a24;
  a15=(a15*a5);
  a13=(a13*a9);
  a15=(a15+a13);
  a15=(a23*a15);
  if (res[0]!=0) res[0][11]=a15;
  a15=arg[2]? arg[2][1] : 0;
  a13=(a0*a15);
  if (res[0]!=0) res[0][12]=a13;
  a13=arg[0]? arg[0][15] : 0;
  a13=(a13-a14);
  a24=(a10*a13);
  a20=arg[0]? arg[0][16] : 0;
  a20=(a20-a18);
  a8=(a12*a20);
  a24=(a24+a8);
  a8=arg[0]? arg[0][17] : 0;
  a8=(a8-a21);
  a1=(a9*a8);
  a24=(a24+a1);
  a1=(a15*a24);
  a17=(a1*a11);
  a16=(a11*a13);
  a25=(a6*a20);
  a16=(a16+a25);
  a25=(a19*a8);
  a16=(a16+a25);
  a25=(a15*a16);
  a26=(a25*a10);
  a17=(a17-a26);
  a17=(a2*a17);
  if (res[0]!=0) res[0][13]=a17;
  a16=(a15*a16);
  a17=(a16*a4);
  a13=(a4*a13);
  a20=(a3*a20);
  a13=(a13+a20);
  a8=(a5*a8);
  a13=(a13-a8);
  a8=(a15*a13);
  a20=(a8*a11);
  a17=(a17-a20);
  a17=(a7*a17);
  if (res[0]!=0) res[0][14]=a17;
  a13=(a15*a13);
  a17=(a13*a10);
  a24=(a15*a24);
  a20=(a24*a4);
  a17=(a17-a20);
  a17=(a23*a17);
  if (res[0]!=0) res[0][15]=a17;
  a17=(a0*a15);
  if (res[0]!=0) res[0][16]=a17;
  a17=(a1*a6);
  a20=(a25*a12);
  a17=(a17-a20);
  a17=(a2*a17);
  if (res[0]!=0) res[0][17]=a17;
  a17=(a16*a3);
  a20=(a8*a6);
  a17=(a17-a20);
  a17=(a7*a17);
  if (res[0]!=0) res[0][18]=a17;
  a17=(a13*a12);
  a20=(a24*a3);
  a17=(a17-a20);
  a17=(a23*a17);
  if (res[0]!=0) res[0][19]=a17;
  a15=(a0*a15);
  if (res[0]!=0) res[0][20]=a15;
  a1=(a1*a19);
  a25=(a25*a9);
  a1=(a1-a25);
  a1=(a2*a1);
  if (res[0]!=0) res[0][21]=a1;
  a16=(a16*a5);
  a8=(a8*a19);
  a16=(a16+a8);
  a16=(a22*a16);
  if (res[0]!=0) res[0][22]=a16;
  a24=(a24*a5);
  a13=(a13*a9);
  a24=(a24+a13);
  a24=(a23*a24);
  if (res[0]!=0) res[0][23]=a24;
  a24=arg[2]? arg[2][2] : 0;
  a13=(a0*a24);
  if (res[0]!=0) res[0][24]=a13;
  a13=arg[0]? arg[0][18] : 0;
  a13=(a13-a14);
  a16=(a10*a13);
  a8=arg[0]? arg[0][19] : 0;
  a8=(a8-a18);
  a1=(a12*a8);
  a16=(a16+a1);
  a1=arg[0]? arg[0][20] : 0;
  a1=(a1-a21);
  a25=(a9*a1);
  a16=(a16+a25);
  a25=(a24*a16);
  a15=(a25*a11);
  a17=(a11*a13);
  a20=(a6*a8);
  a17=(a17+a20);
  a20=(a19*a1);
  a17=(a17+a20);
  a20=(a24*a17);
  a26=(a20*a10);
  a15=(a15-a26);
  a15=(a2*a15);
  if (res[0]!=0) res[0][25]=a15;
  a17=(a24*a17);
  a15=(a17*a4);
  a13=(a4*a13);
  a8=(a3*a8);
  a13=(a13+a8);
  a1=(a5*a1);
  a13=(a13-a1);
  a1=(a24*a13);
  a8=(a1*a11);
  a15=(a15-a8);
  a15=(a7*a15);
  if (res[0]!=0) res[0][26]=a15;
  a13=(a24*a13);
  a15=(a13*a10);
  a16=(a24*a16);
  a8=(a16*a4);
  a15=(a15-a8);
  a15=(a23*a15);
  if (res[0]!=0) res[0][27]=a15;
  a15=(a0*a24);
  if (res[0]!=0) res[0][28]=a15;
  a15=(a25*a6);
  a8=(a20*a12);
  a15=(a15-a8);
  a15=(a2*a15);
  if (res[0]!=0) res[0][29]=a15;
  a15=(a17*a3);
  a8=(a1*a6);
  a15=(a15-a8);
  a15=(a7*a15);
  if (res[0]!=0) res[0][30]=a15;
  a15=(a13*a12);
  a8=(a16*a3);
  a15=(a15-a8);
  a15=(a23*a15);
  if (res[0]!=0) res[0][31]=a15;
  a24=(a0*a24);
  if (res[0]!=0) res[0][32]=a24;
  a25=(a25*a19);
  a20=(a20*a9);
  a25=(a25-a20);
  a25=(a2*a25);
  if (res[0]!=0) res[0][33]=a25;
  a17=(a17*a5);
  a1=(a1*a19);
  a17=(a17+a1);
  a17=(a22*a17);
  if (res[0]!=0) res[0][34]=a17;
  a16=(a16*a5);
  a13=(a13*a9);
  a16=(a16+a13);
  a16=(a23*a16);
  if (res[0]!=0) res[0][35]=a16;
  a16=arg[2]? arg[2][3] : 0;
  a13=(a0*a16);
  if (res[0]!=0) res[0][36]=a13;
  a13=arg[0]? arg[0][21] : 0;
  a13=(a13-a14);
  a14=(a10*a13);
  a17=arg[0]? arg[0][22] : 0;
  a17=(a17-a18);
  a18=(a12*a17);
  a14=(a14+a18);
  a18=arg[0]? arg[0][23] : 0;
  a18=(a18-a21);
  a21=(a9*a18);
  a14=(a14+a21);
  a21=(a16*a14);
  a1=(a21*a11);
  a25=(a11*a13);
  a20=(a6*a17);
  a25=(a25+a20);
  a20=(a19*a18);
  a25=(a25+a20);
  a20=(a16*a25);
  a24=(a20*a10);
  a1=(a1-a24);
  a1=(a2*a1);
  if (res[0]!=0) res[0][37]=a1;
  a25=(a16*a25);
  a1=(a25*a4);
  a13=(a4*a13);
  a17=(a3*a17);
  a13=(a13+a17);
  a18=(a5*a18);
  a13=(a13-a18);
  a18=(a16*a13);
  a11=(a18*a11);
  a1=(a1-a11);
  a1=(a7*a1);
  if (res[0]!=0) res[0][38]=a1;
  a13=(a16*a13);
  a10=(a13*a10);
  a14=(a16*a14);
  a4=(a14*a4);
  a10=(a10-a4);
  a10=(a23*a10);
  if (res[0]!=0) res[0][39]=a10;
  a10=(a0*a16);
  if (res[0]!=0) res[0][40]=a10;
  a10=(a21*a6);
  a4=(a20*a12);
  a10=(a10-a4);
  a10=(a2*a10);
  if (res[0]!=0) res[0][41]=a10;
  a10=(a25*a3);
  a6=(a18*a6);
  a10=(a10-a6);
  a7=(a7*a10);
  if (res[0]!=0) res[0][42]=a7;
  a12=(a13*a12);
  a3=(a14*a3);
  a12=(a12-a3);
  a12=(a23*a12);
  if (res[0]!=0) res[0][43]=a12;
  a0=(a0*a16);
  if (res[0]!=0) res[0][44]=a0;
  a21=(a21*a19);
  a20=(a20*a9);
  a21=(a21-a20);
  a2=(a2*a21);
  if (res[0]!=0) res[0][45]=a2;
  a25=(a25*a5);
  a18=(a18*a19);
  a25=(a25+a18);
  a22=(a22*a25);
  if (res[0]!=0) res[0][46]=a22;
  a14=(a14*a5);
  a13=(a13*a9);
  a14=(a14+a13);
  a23=(a23*a14);
  if (res[0]!=0) res[0][47]=a23;
  a23=1.;
  if (res[0]!=0) res[0][48]=a23;
  if (res[0]!=0) res[0][49]=a23;
  if (res[0]!=0) res[0][50]=a23;
  if (res[0]!=0) res[0][51]=a23;
  if (res[0]!=0) res[0][52]=a23;
  if (res[0]!=0) res[0][53]=a23;
  if (res[0]!=0) res[0][54]=a23;
  if (res[0]!=0) res[0][55]=a23;
  if (res[0]!=0) res[0][56]=a23;
  if (res[0]!=0) res[0][57]=a23;
  if (res[0]!=0) res[0][58]=a23;
  if (res[0]!=0) res[0][59]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_LQR_B_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_LQR_B_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_LQR_B_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_LQR_B_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_LQR_B_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_LQR_B_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_LQR_B_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_LQR_B_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_LQR_B_func_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_LQR_B_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_LQR_B_func_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_LQR_B_func_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_LQR_B_func_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_LQR_B_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_LQR_B_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_LQR_B_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_quad_LQR_B_func(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i, j;
  casadi_real w[139];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"quad_LQR_B_func\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"quad_LQR_B_func\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+112);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+24, casadi_s0, w+112);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+48, casadi_s1, w+112);
  --resc;
  res[0] = w+52;
  i = quad_LQR_B_func(arg, res, iw, w+112, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"quad_LQR_B_func\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s2, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[16];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "quad_LQR_B_func")==0) {
    mex_quad_LQR_B_func(resc, resv, argc, argv);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'quad_LQR_B_func'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
