function x_d = quad_get_xd_from_traj(t,t_list,...
    com_pos_list, com_vel_list, com_angle_list, com_angle_vel_list,...
    foot_pos_list, foot_vel_list, foot_acc_list, foot_force_list, contact_list,...
    param)
% assemble an x_d vector from input trajectories
% t must be within 0 to param.total_time
% other lists must be generated by quad_generate_trajectory_lists.m

com_pos_d = interp1(t_list,com_pos_list',t)';
com_ang_d = interp1(t_list,com_angle_list',t)';
roll_ang  = com_ang_d(1);
pitch_ang = com_ang_d(2);
yaw_ang   = com_ang_d(3);
com_vel = interp1(t_list,com_vel_list',t)';
com_ang_vel_d = interp1(t_list,com_angle_vel_list',t)';
B = [1  0 -sin(pitch_ang);
     0  cos(roll_ang) sin(roll_ang)*cos(pitch_ang);
     0 -sin(roll_ang) cos(roll_ang)*cos(pitch_ang)];
wb_d = B*com_ang_vel_d;
p_e_d = zeros(3,param.leg_num); % foot pose in earth frame
for i=1:param.leg_num
   foot_pos_leg_list = squeeze(foot_pos_list(i,:,:));
   p_e_d(:,i) = interp1(t_list,foot_pos_leg_list',t)';
end

contact_d = interp1(t_list,contact_list',t)'; 
x_d = [com_pos_d; com_ang_d; com_vel; wb_d; reshape(p_e_d,3*param.leg_num,1);contact_d];

end