function u_d = quad_get_ud_from_traj(t,t_list,...
    com_pos_list, com_vel_list, com_angle_list, com_angle_vel_list,...
    foot_pos_list, foot_vel_list, foot_acc_list, foot_force_list, contact_list,...
    param)
% assemble an x_d vector from input trajectories
% t must be within 0 to param.total_time
% other lists must be generated by quad_generate_trajectory_lists.m


p_vel_e_d = zeros(3,param.leg_num); % foot vel in earth frame
for i=1:param.leg_num
   foot_vel_leg_list = squeeze(foot_vel_list(i,:,:));
   p_vel_e_d(:,i) = interp1(t_list,foot_vel_leg_list',t)';
end
F_e_d = zeros(3,param.leg_num); % foot vel in earth frame
for i=1:param.leg_num
   foot_force_leg_list = squeeze(foot_force_list(i,:,:));
   F_e_d(:,i) = interp1(t_list,foot_force_leg_list',t)';
end

contact_d = interp1(t_list,contact_list',t)'; 
u_d = [reshape(F_e_d,3*param.leg_num,1); reshape(p_vel_e_d,3*param.leg_num,1);contact_d];

end