function [obj ,obj_grad] = quad_optimal_transition_objective(...
    state, ...
    robot_state1, robot_state2,...
    param, ...
    casadi_quad_sx_obj_func, casadi_quad_sx_obj_grad_func)

addpath('../CasADi')
import casadi.*
com_pos_start = robot_state1(1:3);
com_pos_end = robot_state2(1:3);
com_ang_start = robot_state1(4:6);
com_ang_end = robot_state2(4:6);
p_e_start = quad_optimal_transition_get_foot_pos_from_state(robot_state1, param);
p_e_end = quad_optimal_transition_get_foot_pos_from_state(robot_state2, param);

full_state = state;

rst1 = casadi_quad_sx_obj_func('state', full_state,...
                      'pos_start', p_e_start,...
                      'pos_end', p_e_end,...
                      'com_start', com_pos_start,...
                      'com_end', com_pos_end,...
                      'com_ang_start', com_ang_start,...
                      'com_ang_end', com_ang_end);  
                  
obj = full(rst1.obj);

if nargout > 1
    rst2 = casadi_quad_sx_obj_grad_func('state', full_state,...
                          'pos_start', p_e_start,...
                          'pos_end', p_e_end,...
                          'com_start', com_pos_start,...
                          'com_end', com_pos_end,...
                          'com_ang_start', com_ang_start,...
                          'com_ang_end', com_ang_end);  

    obj_grad = full(rst2.obj_grad);
end

end